---
dist: xenial
language: java
before_deploy:
  - ./gradlew sourcesJar generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: bintray.json
  user: $BINTRAY_USERNAME
  key: $BINTRAY_API_KEY
  skip_cleanup: true
  on:
    tags: true
