---
on:
  push:
    tags:
      - "*"

jobs:
  "publish":

    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      packages: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-java@v3"
        with:
          java-version: "11"
          distribution: "temurin"

      - uses: "gradle/gradle-build-action@v2"
        with:
          arguments: "build"

      - uses: "gradle/gradle-build-action@v2"
        with:
          arguments: "publish"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
